apiVersion: 1

datasources:
  - name: Elasticsearch - Anomalies
    type: elasticsearch
    uid: elasticsearch-anomalies
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: "anomalies"
      timeField: "detected_at"
    editable: false
