apiVersion: 1

datasources:
  - name: Elasticsearch - Logs
    type: elasticsearch
    uid: elasticsearch-logs
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: "logs-*"
      timeField: "@timestamp"
      logMessageField: "message"
      logLevelField: "level"
    editable: false

  - name: Elasticsearch - Anomalies
    type: elasticsearch
    uid: elasticsearch-anomalies
    access: proxy
    url: http://elasticsearch:9200
    jsonData:
      index: "anomalies"
      timeField: "detected_at"
    editable: false
